import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.skip();
  await page.goto('https://www.automationexercise.com/');
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Greame');
  await page.getByRole('textbox', { name: 'Name' }).press('Tab');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('greame.123@yopmail.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByRole('radio', { name: 'Mr.' }).check();
  await page.getByRole('textbox', { name: 'Name *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('Password@123');
  await page.locator('#days').selectOption('13');
  await page.locator('#months').selectOption('4');
  await page.locator('#years').selectOption('1997');
  await page.getByRole('textbox', { name: 'First name *' }).click();
  await page.getByRole('textbox', { name: 'First name *' }).fill('Greame');
  await page.getByRole('textbox', { name: 'First name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last name *' }).fill('Smith');
  await page.getByRole('textbox', { name: 'Company', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).click();
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('123 park avenue');
  await page.getByRole('paragraph').filter({ hasText: 'City *' }).click();
  await page.getByRole('textbox', { name: 'State *' }).click();
  await page.getByRole('textbox', { name: 'State *' }).fill('TN');
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).click();
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('Chennai');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('600001');
  await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('1234567890');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.getByRole('link', { name: ' Logout' }).click();
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').fill('greame.123@yopmail.com');
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Password@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Logged in as Greame').click();
  await page.getByRole('link', { name: ' Cart' }).click();
  await page.getByText('Cart is empty! Click here to').click();
  await page.getByRole('link', { name: ' Home' }).click();
  await page.locator('.overlay-content > .btn').first().click();
  await page.getByText('').click();
  await page.getByRole('heading', { name: 'Added!' }).click();
  await page.getByText('Your product has been added').click();
  await page.getByRole('paragraph').filter({ hasText: 'View Cart' }).click();
  await page.getByText('Women > Tops').click();
  await page.getByRole('cell', { name: 'Product Image' }).click();
  await page.getByText('Rs.').first().click();
  await page.getByRole('button', { name: '1' }).click();
  await page.getByRole('cell', { name: 'Quantity' }).click();
  await page.getByRole('cell', { name: '1' }).click();
  await page.getByText('Proceed To Checkout').click();
  await page.locator('#address_delivery').getByText('Mr. Greame Smith').click();
  await page.locator('#address_delivery').getByText('park avenue').click();
  await page.locator('#address_delivery').getByText('Chennai TN').click();
  await page.locator('#address_delivery').getByText('India').click();
  await page.locator('#address_delivery').getByText('1234567890').click();
  await page.locator('#address_invoice').getByText('Mr. Greame Smith').click();
  await page.getByText('Your billing address Mr.').click();
  await page.getByRole('heading', { name: 'Review Your Order' }).click();
  await page.getByText('Women > Tops').click();
  await page.getByRole('link', { name: 'Product Image' }).click();
  await page.getByText('Proceed To Checkout').click();
  await page.getByRole('cell', { name: 'Blue Top Women > Tops' }).click();
  await page.getByRole('cell', { name: 'Price' }).click();
  await page.getByRole('cell', { name: 'Quantity' }).click();
  await page.getByRole('cell', { name: 'Total', exact: true }).click();
  await page.getByRole('link', { name: 'Place Order' }).click();
  await page.locator('input[name="name_on_card"]').click();
  await page.locator('input[name="name_on_card"]').fill('4111111111111111');
  await page.locator('input[name="name_on_card"]').click();
  await page.locator('input[name="name_on_card"]').fill('Greame');
  await page.locator('input[name="card_number"]').click();
  await page.locator('input[name="card_number"]').fill('4111111111111111');
  await page.getByRole('textbox', { name: 'ex.' }).click();
  await page.getByRole('textbox', { name: 'ex.' }).fill('123');
  await page.getByRole('textbox', { name: 'MM' }).click();
  await page.getByRole('textbox', { name: 'MM' }).fill('08');
  await page.getByRole('textbox', { name: 'YYYY' }).click();
  await page.getByRole('textbox', { name: 'YYYY' }).fill('2030');
  await page.getByRole('button', { name: 'Pay and Confirm Order' }).click();
  await page.getByText('Order Placed! Congratulations').click();
  await page.getByText('Congratulations! Your order').click();
  await page.getByText('Order Placed!').click();
  await page.getByRole('link', { name: ' Cart' }).click();
  await page.getByRole('link', { name: 'Cart', exact: true }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Cart is empty! Click here to').click();
  await page.getByRole('link', { name: ' Logout' }).click();
});